### ISSUE TITLE
Yopl looks neat. Do you have some examples?

### ISSUE THREAD

**Issue by canadaduane** [uhop/yopl#47]
I'm curious if you have some examples. It looks clean and well-integrated as a DSL for javascript.

**Comment by uhop** [comment]
Unfortunately all I have at the moment is in [tests](https://github.com/uhop/yopl/tree/master/tests). And the documentation is pending.

The project itself is a recreation of my old project `yocto-prolog`, which provided an embedded prolog-like DSL in C++ and included a parser to consume programs in a prolog-like syntax, so the rules can be authored and loaded externally.

The heart of the project is a small unification library I wrote before, which is documented in a series of blog posts (can be found in the [wiki](https://github.com/uhop/yopl/wiki)). [deep6](https://github.com/uhop/deep6/wiki) is a face lift of that library + handling of circular references + generations, so it is possible to do the backtracking going to a previous generation. `yopl` just a simple logical solver on top of that.
